hosts:
  - name: cloudflare
    address: ${CLOUDFLARE_ADDRESS}
    deploy_dir: /opt/apps

  - name: pangolin
    address: ${PANGOLIN_ADDRESS}
    deploy_dir: /opt/apps

  - name: nginxproxymanager
    address: ${NPM_ADDRESS}
    deploy_dir: /opt/apps

  - name: openwebui
    address: ${OPENWEBUI_ADDRESS}
    deploy_dir: /opt/apps

  - name: atuin
    address: ${ATUIN_ADDRESS}
    deploy_dir: /opt/apps

  - name: syncthing
    address: ${SYNCTHING_ADDRESS}
    deploy_dir: /opt/apps

repos:
  - name: homelab-deployments
    url: git@github.com:jancernik/homelab-deployments.git
    trigger_mode: hybrid
    poll_interval: 60s

projects:
  - name: cloudflare
    repo: homelab-deployments
    repo_subdir: cloudflare
    targets:
      - cloudflare

  - name: pangolin
    repo: homelab-deployments
    repo_subdir: pangolin
    targets:
      - pangolin

  - name: nginxproxymanager
    repo: homelab-deployments
    repo_subdir: nginxproxymanager
    targets:
      - nginxproxymanager

  - name: openwebui
    repo: homelab-deployments
    repo_subdir: openwebui
    targets:
      - openwebui

  - name: atuin
    repo: homelab-deployments
    repo_subdir: atuin
    targets:
      - atuin

  - name: syncthing
    repo: homelab-deployments
    repo_subdir: syncthing
    targets:
      - syncthing