services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    volumes:
      - /srv/openwebui:/app/backend/data
