x-common: &common
  image: lscr.io/linuxserver/syncthing:latest
  restart: unless-stopped
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Buenos_Aires

services:
  syncthing:
    <<: *common
    container_name: syncthing
    hostname: syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      #- 21027:21027/udp
    volumes:
      - /mnt/data:/data
      - /srv/syncthing/config:/config

  syncthing-tom:
    <<: *common
    container_name: syncthing-tom
    hostname: syncthing-tom
    ports:
      - 8385:8384
      - 22001:22000/tcp
      - 22001:22000/udp
      #- 21028:21027/udp
    volumes:
      - /mnt/data/TOM:/data
      - /srv/syncthing-tom/config:/config
